### ISSUE TITLE
workspacer crashes after locking desktop

### ISSUE THREAD

**Issue by mhegreberg** [workspacer/workspacer#250]
if I lock my desktop and walk away, most of the time when I return is seems that workspacer crashes. 

reopening workspacer doesn't initially work, as it won't detect any of the windows. I have to open workspacer again, close it fully, then reopen it.

when I do this, unfortunately, I have to re place any windows I have open.

I'm happy to attatch logs, I'm just not sure where workspacer puts them

thank you!

**Comment by dalyIsaac** [comment]
I'm guessing this is due to https://github.com/workspacer/workspacer/blob/master/src/workspacer/ConfigContext.cs#L224-L235

This would definitely be something to fix in the future.

This has the same root cause as #172.

**Comment by priorax** [comment]
I know I'm late, but just started using workspacer and had this happen to me
Stack trace I found for this
```
Application: workspacer.Watcher.exe
CoreCLR Version: 5.0.1722.21314
.NET Version: 5.0.17
Description: The process was terminated due to an unhandled exception.
Exception Info: System.OverflowException: Arithmetic operation resulted in an overflow.
   at System.IntPtr.op_Explicit(IntPtr value)
   at workspacer.ConsoleHelper.get_IsConsoleShowing()
   at workspacer.ConsoleHelper.set_IsConsoleShowing(Boolean value)
   at workspacer.ConsoleHelper.Initialize()
   at workspacer.Watcher.Program.Main(String[] args)
```
