### ISSUE TITLE
not able to import a new layout

### ISSUE THREAD

**Issue by schulzalbrecht** [workspacer/workspacer#260]
I installed the program and create the config fiile (workspacer.config.csx). 
Now I'm trying to add the `PaneLayoutEngine`, so I added the line `context.DefaultLayouts = () => new ILayoutEngine[] { new PaneLayoutEngine() };` in the config file as suggested on the website/config. 

My entire config files looks like: 
```csharp
#r "C:\Program Files\workspacer\workspacer.Shared.dll"
#r "C:\Program Files\workspacer\plugins\workspacer.Bar\workspacer.Bar.dll"
#r "C:\Program Files\workspacer\plugins\workspacer.ActionMenu\workspacer.ActionMenu.dll"
#r "C:\Program Files\workspacer\plugins\workspacer.FocusIndicator\workspacer.FocusIndicator.dll"

using System;
using workspacer;
using workspacer.Bar;
using workspacer.ActionMenu;
using workspacer.FocusIndicator;

Action<IConfigContext> doConfig = (context) =>
{
    // Uncomment to switch update branch (or to disable updates)
    //context.Branch = Branch.None

    context.AddBar();
    context.AddFocusIndicator();
    var actionMenu = context.AddActionMenu();

    context.WorkspaceContainer.CreateWorkspaces("one", "two", "three", "four", "five");

   context.DefaultLayouts = () => new ILayoutEngine[] { new PaneLayoutEngine() };              // ***new line***
};
return doConfig;
```

As soon as I start the program, the below error is thrown:
```txt
Microsoft.CodeAnalysis.Scripting.CompilationErrorException: (23,57): error CS0144: An instance of the abstract type or abstract interface "PaneLayoutEngine" cannot be created.
   at Microsoft.CodeAnalysis.Scripting.ScriptBuilder.ThrowIfAnyCompilationErrors(DiagnosticBag diagnostics, DiagnosticFormatter formatter)
   at Microsoft.CodeAnalysis.Scripting.ScriptBuilder.CreateExecutor[T](ScriptCompiler compiler, Compilation compilation, Boolean emitDebugInformation, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Scripting.Script`1.GetExecutor(CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Scripting.Script`1.RunAsync(Object globals, Func`2 catchException, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Scripting.Script`1.RunAsync(Object globals, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.CSharp.Scripting.CSharpScript.RunAsync[T](String code, ScriptOptions options, Object globals, Type globalsType, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.CSharp.Scripting.CSharpScript.EvaluateAsync[T](String code, ScriptOptions options, Object globals, Type globalsType, CancellationToken cancellationToken)
   at workspacer.ConfigHelper.DoConfig(IConfigContext context)
   at workspacer.workspacer.Start()
   at workspacer.Program.Run()
   at workspacer.Program.Main(String[] args)
```

**Comment by dalyIsaac** [comment]
`PaneLayoutEngine` is an abstract class, and thus cannot be instantiated. You need to use either `VertLayoutEngine` or `HorzLayoutEngine`.
