### ISSUE TITLE
I am trying to add gaps between windows, getting errors. 

### ISSUE THREAD

**Issue by Mesum-Hussain** [workspacer/workspacer#285]
I followed the instructions given on the website and modified my workspacer.config.csx accordingly. But I am getting some errors. 

`Microsoft.CodeAnalysis.Scripting.CompilationErrorException: (5,1): error CS0006: Metadata file 'C:\Program Files\workspacer\plugins\workspacer.Gap\workspacer.Gap.dll' could not be found
   at Microsoft.CodeAnalysis.Scripting.ScriptBuilder.ThrowIfAnyCompilationErrors(DiagnosticBag diagnostics, DiagnosticFormatter formatter)
   at Microsoft.CodeAnalysis.Scripting.ScriptBuilder.CreateExecutor[T](ScriptCompiler compiler, Compilation compilation, Boolean emitDebugInformation, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Scripting.Script 1.GetExecutor(CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Scripting.Script 1.RunAsync(Object globals, Func 2 catchException, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Scripting.Script 1.RunAsync(Object globals, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.CSharp.Scripting.CSharpScript.RunAsync[T](String code, ScriptOptions options, Object globals, Type globalsType, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.CSharp.Scripting.CSharpScript.EvaluateAsync[T](String code, ScriptOptions options, Object globals, Type globalsType, CancellationToken cancellationToken)
   at workspacer.ConfigHelper.DoConfig(IConfigContext context)
   at workspacer.workspacer.Start()
   at workspacer.Program.Run()
   at workspacer.Program.Main(String[] args)
`

Please help.

**Comment by josteink** [comment]
Are you talking about this example? https://workspacer.org/config/#gaps

If so, the error clearly states that the file `C:\Program Files\workspacer\plugins\workspacer.Gap\workspacer.Gap.dll` could not be found.

Have you checked if it's actually there? Maybe you installed to another path and need to adjust the path in the first line? :smile:

**Comment by maltedickson** [comment]
I have the same problem.

How can I get the `workspacer.Gap.dll` file?

**Comment by thiag0mei** [comment]
I believe gaps is only available to the unstable branch. Are you using the unstable branch?
