### ISSUE TITLE
Overflow Exception when running on Win 11 x64

### ISSUE THREAD

**Issue by KenMercusLai** [workspacer/workspacer#347]
I'm facing the issue on one of my laptops that is running Win 11Home x64 10.0.22 Build 22000

Unhandled exception. System.OverflowException: Arithmetic operation resulted in an overflow.
   at System.IntPtr.op_Explicit(IntPtr value)
   at workspacer.ConsoleHelper.get_IsConsoleShowing() in D:\a\workspacer\workspacer\src\workspacer.Watcher\ConsoleHelper.cs:line 35
   at workspacer.ConsoleHelper.set_IsConsoleShowing(Boolean value) in D:\a\workspacer\workspacer\src\workspacer.Watcher\ConsoleHelper.cs:line 46
   at workspacer.ConsoleHelper.Initialize() in D:\a\workspacer\workspacer\src\workspacer.Watcher\ConsoleHelper.cs:line 25
   at workspacer.Watcher.Program.Main(String[] args) in D:\a\workspacer\workspacer\src\workspacer.Watcher\Program.cs:line 19

**Comment by KenMercusLai** [comment]
I've submitted #348 for fixing the issue.

**Comment by AhmedMahmud** [comment]
I see you guys have made a PR for the fix which is great. Will there be a new release any time soon, or should I try figuring out building it myself?
