### ISSUE TITLE
Latest unstable version (v0.9.12) doesn't launch

### ISSUE THREAD

**Issue by marad** [workspacer/workspacer#375]
Is this something that may have surfaced after merging #369?
```
Microsoft.CodeAnalysis.Scripting.CompilationErrorException: error CS0400: Nie mo┐na odnalečŠ nazwy typu lub przestrzeni nazw äSystem.Action`1[[workspacer.IConfigContext, workspacer.Shared, Version=0.9.12.0, Culture=neutral, PublicKeyToken=null]], System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798eö w globalnej przestrzeni nazw (czy nie brakuje odwo│ania do zestawu?)
   at Microsoft.CodeAnalysis.Scripting.ScriptBuilder.ThrowIfAnyCompilationErrors(DiagnosticBag diagnostics, DiagnosticFormatter formatter)
   at Microsoft.CodeAnalysis.Scripting.ScriptBuilder.CreateExecutor[T](ScriptCompiler compiler, Compilation compilation, Boolean emitDebugInformation, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Scripting.Script`1.GetExecutor(CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Scripting.Script`1.RunAsync(Object globals, Func`2 catchException, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Scripting.Script`1.RunAsync(Object globals, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.CSharp.Scripting.CSharpScript.RunAsync[T](String code, ScriptOptions options, Object globals, Type globalsType, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.CSharp.Scripting.CSharpScript.EvaluateAsync[T](String code, ScriptOptions options, Object globals, Type globalsType, CancellationToken cancellationToken)
   at workspacer.ConfigHelper.DoConfig(IConfigContext context) in D:\a\workspacer\workspacer\src\workspacer\Config\ConfigHelper.cs:line 63
   at workspacer.workspacer.Start() in D:\a\workspacer\workspacer\src\workspacer\Workspacer.cs:line 53
   at workspacer.Program.Run() in D:\a\workspacer\workspacer\src\workspacer\Program.cs:line 148
   at workspacer.Program.Main(String[] args) in D:\a\workspacer\workspacer\src\workspacer\Program.cs:line 73
```

**Comment by Zinvoke** [comment]
Can you share your workspacer.config.csx file? I believe this is an issue with the configuration and not the release

**Comment by marad** [comment]
@Zinvoke I'm using latest stable version and it's ok. With the unstable version I get this error.

My config is pretty simple:

```c#
#r "C:\apps\workspacer\workspacer.Shared.dll"
#r "C:\apps\workspacer\plugins\workspacer.Bar\workspacer.Bar.dll"
#r "C:\apps\workspacer\plugins\workspacer.ActionMenu\workspacer.ActionMenu.dll"
#r "C:\apps\workspacer\plugins\workspacer.FocusIndicator\workspacer.FocusIndicator.dll"
#r "C:\apps\workspacer\plugins\workspacer.TitleBar\workspacer.TitleBar.dll"
#r "C:\apps\workspacer\plugins\workspacer.Gap\workspacer.Gap.dll"

using System;
using workspacer;
using workspacer.Bar;
using workspacer.Bar.Widgets;
using workspacer.ActionMenu;
using workspacer.FocusIndicator;
using workspacer.Gap;


Action<IConfigContext> doConfig = (context) =>
{

    // Uncomment to switch update branch (or to disable updates)
    //context.Branch = Branch.None;

    context.AddBar(new BarPluginConfig() {
        BarTitle = "workspacer.Bar",
        FontSize = 14,
        FontName = "Segoe UI",
        RightWidgets = () => new IBarWidget[] { 
            new TaskWdiget(),
            new TimeWidget(1000, "HH:mm"),
            new ActiveLayoutWidget()
        }
    });
    context.AddFocusIndicator();
    var actionMenu = context.AddActionMenu();
    actionMenu.DefaultMenu.AddFreeForm("hello", (s) => Console.WriteLine(s));


    context.AddGap(
        new GapPluginConfig()
        {
            InnerGap = 10,
            OuterGap = 5,
            Delta = 5
        }
    );

    context.DefaultLayouts = () => new ILayoutEngine[] { 
        new DwindleLayoutEngine(),
        new TallLayoutEngine() 
    };


    context.WorkspaceContainer.CreateWorkspaces("1", "2", "3", "4", "5", "6", "7");
    context.WorkspaceContainer.CreateWorkspaces("Zoom", "Music", "IM");
    context.Keybinds.Subscribe(KeyModifiers.Alt, Keys.D0, () => {
        context.Workspaces.SwitchToWorkspace(9);
    });
    context.CanMinimizeWindows = true; // false by default

    context.WindowRouter.AddRoute(WindowRouter(context, WindowToDesktopMapping));
    context.WindowRouter.AddFilter(ShouldTileWindow);
    

    context.Keybinds.Subscribe(KeyModifiers.Alt, Keys.Z, () => {
        context.ToggleConsoleWindow();
    });
    context.Keybinds.Subscribe(KeyModifiers.Alt, Keys.F11, () => {
        var window = context.Workspaces.FocusedWorkspace.FocusedWindow;
        if (window.IsMaximized) {
            window.ShowNormal();
        } else {
            window.ShowMaximized();
        }
    });
    

    context.Keybinds.Unsubscribe(KeyModifiers.Alt, Keys.Enter);

};
return doConfig;


public Func<IWindow, IWorkspace> WindowRouter(
    IConfigContext context,
    Func<IWindow, string> mappings
) {
    return (window) => {
        var workspaceName = mappings(window);
        if (workspaceName == null) {
            return null;
        } else {
            return context.WorkspaceContainer[workspaceName];
        }
    };
}

public string WindowToDesktopMapping(IWindow window) {
    /**/ if (window.Title.Contains("Zoom")) return "Zoom";
    else if (window.Title.Contains("YouTube Music")) return "Music";
    else if (window.Title.Contains("WhatsApp")) return "IM";
    else if (window.Title.Contains("Messenger")) return "IM";
    else if (window.Title.Contains("MTGA")) return "5";
    else return null;
}

public Boolean ShouldTileWindow(IWindow window) {
    return !ShouldSkipWindow(window);
}

public Boolean ShouldSkipWindow(IWindow window) {
    return window.Class.Contains("SunAwtWindow") 
        || window.Title.Contains("Window Spy")
        || window.Class.Contains("GlassWndClass-GlassWindowClass");
}

public class TaskWdiget : workspacer.Bar.BarWidgetBase
{
    private int index = 0;
    private string[] msgs = {
        "hello",
        "world"
    };
    public TaskWdiget() {

    }

    public override workspacer.Bar.IBarWidgetPart[] GetParts() {
        return Parts(Part(msgs[index], partClicked: () => {
            index = (index+1) % msgs.Length;
            MarkDirty();
        }));
    }

    public override void Initialize() {
    }
}

```

**Comment by Zinvoke** [comment]
![Untitled](https://user-images.githubusercontent.com/84819317/194783304-f07fba18-a4df-4c01-81e2-1b728af444aa.png)
The latest version compiled is working for me fine I would check your reference path's

```cs
#r "C:\Workspacer\src\workspacer\bin\Release\net5.0-windows\win10-x64\workspacer.Shared.dll"
#r "C:\Workspacer\src\workspacer\bin\Release\net5.0-windows\win10-x64\plugins\workspacer.Bar\workspacer.Bar.dll"
#r "C:\Workspacer\src\workspacer\bin\Release\net5.0-windows\win10-x64\plugins\workspacer.ActionMenu\workspacer.ActionMenu.dll"
#r "C:\Workspacer\src\workspacer\bin\Release\net5.0-windows\win10-x64\plugins\workspacer.FocusIndicator\workspacer.FocusIndicator.dll"
#r "C:\Workspacer\src\workspacer\bin\Release\net5.0-windows\win10-x64\plugins\workspacer.TitleBar\workspacer.TitleBar.dll"
#r "C:\Workspacer\src\workspacer\bin\Release\net5.0-windows\win10-x64\plugins\workspacer.Gap\workspacer.Gap.dll"

using System;
using workspacer;
using workspacer.Bar;
using workspacer.Bar.Widgets;
using workspacer.ActionMenu;
using workspacer.FocusIndicator;
using workspacer.Gap;


Action<IConfigContext> doConfig = (context) =>
{

    // Uncomment to switch update branch (or to disable updates)
    //context.Branch = Branch.None;

    context.AddBar(new BarPluginConfig() {
        BarTitle = "workspacer.Bar",
        FontSize = 14,
        FontName = "Segoe UI",
        RightWidgets = () => new IBarWidget[] { 
            new TaskWdiget(),
            new TimeWidget(1000, "HH:mm"),
            new ActiveLayoutWidget()
        }
    });
    context.AddFocusIndicator();
    var actionMenu = context.AddActionMenu();
    actionMenu.DefaultMenu.AddFreeForm("hello", (s) => Console.WriteLine(s));


    context.AddGap(
        new GapPluginConfig()
        {
            InnerGap = 10,
            OuterGap = 5,
            Delta = 5
        }
    );

    context.DefaultLayouts = () => new ILayoutEngine[] { 
        new DwindleLayoutEngine(),
        new TallLayoutEngine() 
    };


    context.WorkspaceContainer.CreateWorkspaces("1", "2", "3", "4", "5", "6", "7");
    context.WorkspaceContainer.CreateWorkspaces("Zoom", "Music", "IM");
    context.Keybinds.Subscribe(KeyModifiers.Alt, Keys.D0, () => {
        context.Workspaces.SwitchToWorkspace(9);
    });
    context.CanMinimizeWindows = true; // false by default

    context.WindowRouter.AddRoute(WindowRouter(context, WindowToDesktopMapping));
    context.WindowRouter.AddFilter(ShouldTileWindow);
    

    context.Keybinds.Subscribe(KeyModifiers.Alt, Keys.Z, () => {
        context.ToggleConsoleWindow();
    });
    context.Keybinds.Subscribe(KeyModifiers.Alt, Keys.F11, () => {
        var window = context.Workspaces.FocusedWorkspace.FocusedWindow;
        if (window.IsMaximized) {
            window.ShowNormal();
        } else {
            window.ShowMaximized();
        }
    });
    

    context.Keybinds.Unsubscribe(KeyModifiers.Alt, Keys.Enter);

};
return doConfig;


public Func<IWindow, IWorkspace> WindowRouter(
    IConfigContext context,
    Func<IWindow, string> mappings
) {
    return (window) => {
        var workspaceName = mappings(window);
        if (workspaceName == null) {
            return null;
        } else {
            return context.WorkspaceContainer[workspaceName];
        }
    };
}

public string WindowToDesktopMapping(IWindow window) {
    /**/ if (window.Title.Contains("Zoom")) return "Zoom";
    else if (window.Title.Contains("YouTube Music")) return "Music";
    else if (window.Title.Contains("WhatsApp")) return "IM";
    else if (window.Title.Contains("Messenger")) return "IM";
    else if (window.Title.Contains("MTGA")) return "5";
    else return null;
}

public Boolean ShouldTileWindow(IWindow window) {
    return !ShouldSkipWindow(window);
}

public Boolean ShouldSkipWindow(IWindow window) {
    return window.Class.Contains("SunAwtWindow") 
        || window.Title.Contains("Window Spy")
        || window.Class.Contains("GlassWndClass-GlassWindowClass");
}

public class TaskWdiget : workspacer.Bar.BarWidgetBase
{
    private int index = 0;
    private string[] msgs = {
        "hello",
        "world"
    };
    public TaskWdiget() {

    }

    public override workspacer.Bar.IBarWidgetPart[] GetParts() {
        return Parts(Part(msgs[index], partClicked: () => {
            index = (index+1) % msgs.Length;
            MarkDirty();
        }));
    }

    public override void Initialize() {
    }
}
```

**Comment by marad** [comment]
DLLs are all in correct places. I don't think it's config related. Maybe it's environment related? Maybe you have something installed that I don't and the DLLs try to use that?

The error in english would be something like this:

```
The type or namespace name 'System.Action`1[...]' could not be found in the global namespace (are you missing an assembly reference?)
```

In my config I have not used any global name `System.Action` so I'm pretty clueless as to why it does not work. Also keep in mind that this config **WORKS** with previous version of Workspacer.

**Comment by josteink** [comment]
If you are using function-valued parameters anywhere, you are implicitly creating `System.Action` instances.

````c#
var x = "123"; // System.String

var y = () =>
{
   Console.WriteLine("Hey there!"
}; // System.Action
````

That said, I'd consider it weird if System-references are not implicit or working.

**Comment by pranavpa8788** [comment]
@Zinvoke totally unrelated question to this issue. But, are you Windows 11? If so, what task bar and icon theme are those?

**Comment by marad** [comment]
Okay, I've done some tests and this must be related to my build environment. 

* If I remove the config file completely, workspacer starts ok
* If I create completely empty `workspacer.config.csx` then it fails with this message

I'm not C#-native so I have no idea how to even debug this further. Do you have any ideas?

**Comment by josteink** [comment]
CC: @tlsomers 

Do you think this could be related to your F# changes?

**Comment by tlsomers** [comment]
Seeing as plugins don't do anything until they're activated, it's not likely to be the case. I'm guessing it might be using a different .net SDK or runtime somehow. Will investigate later today or tomorrow

**Comment by melMass** [comment]
Hi, I'm having the exact same issue on windows 10

![image](https://user-images.githubusercontent.com/7041726/200133614-a5dd4bbd-a160-4f76-91ef-a8d03525ecab.png)

**Comment by melMass** [comment]
I found the issue!!
My scoop install was conflicting with the release msi one:

```zsh
scoop uninstall workspacer
```
