### ISSUE TITLE
[BUG] Using winget to install workspacer in another drive

### ISSUE THREAD

**Issue by dantearaujo1** [workspacer/workspacer#438]
Can't run workspacer if is installed in another drive using winget install --id rickbutton.workspacer.beta -i

This is the exception recieved:

Microsoft.CodeAnalysis.Scripting.CompilationErrorException: (10,1): error CS0006: Arquivo de origem "C:\Program Files\workspacer\workspacer.Shared.dll" couldn't be found
   at Microsoft.CodeAnalysis.Scripting.ScriptBuilder.ThrowIfAnyCompilationErrors(DiagnosticBag diagnostics, DiagnosticFormatter formatter)
   at Microsoft.CodeAnalysis.Scripting.ScriptBuilder.CreateExecutor[T](ScriptCompiler compiler, Compilation compilation, Boolean emitDebugInformation, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Scripting.Script`1.GetExecutor(CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Scripting.Script`1.RunAsync(Object globals, Func`2 catchException, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Scripting.Script`1.RunAsync(Object globals, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.CSharp.Scripting.CSharpScript.RunAsync[T](String code, ScriptOptions options, Object globals, Type globalsType, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.CSharp.Scripting.CSharpScript.EvaluateAsync[T](String code, ScriptOptions options, Object globals, Type globalsType, CancellationToken cancellationToken)
   at workspacer.ConfigHelper.DoConfig(IConfigContext context)
   at workspacer.workspacer.Start()
   at workspacer.Program.Run()
   at workspacer.Program.Main(String[] args)

**Comment by josteink** [comment]
Hey there and thanks for the bug-report.

Since the bug-report is not entirely complete, I will make some assumptions:

* workspacer is installed, but has not yet been configured with an explicit config-file
* this the default config template is used
* something fails when trying to build this template

IF that is the situation, I'm not quite sure what happens here:

* The [config-template](https://github.com/workspacer/workspacer/blob/master/src/workspacer/Config/workspacer.config.template.csx) applied contains a placeholder variable which gets replaced at runtime (`WORKSPACER_PATH`).
* This [gets replaced](https://github.com/workspacer/workspacer/blob/082c786c3efa465fbdd64d2dbbc86a21d8666cdc/src/workspacer/Config/ConfigHelper.cs#L48-L49) with the location of the current assembly.
* Which should be the same folder which you installed workspacer in, right?

Or are some of my assumptions here incorrect?

**Comment by josteink** [comment]
Ah. So you had a previous installation, for which a config was created. And then later you installed in a different location, but with the old config in place.

That could probably cause issues like this, yes.

I honestly don't think this is a common enough issue to warrant and code-changes or updates... So unless you are willing to send a PR for this yourself, I'm going to close this issue as resolved. 

Is that OK with you?

**Comment by dantearaujo1** [comment]
Yes, its ok to me! thx
