### ISSUE TITLE
Connecting or Disconnecting screens breaks the app

### ISSUE THREAD

**Issue by MarkStruik** [workspacer/workspacer#493]
After disconnecting and connecting my screen the application hard breaks:

``` shell
2023-10-13 10:41:35.8553|FATAL|workspacer.Program|exception occurred, quitting workspacer: System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')
   at System.Collections.Generic.List`1.set_Item(Int32 index, T value)
   at workspacer.Workspace.SwapWindows(IWindow left, IWindow right)
   at workspacer.WorkspaceManager.TrySwapWindowToMouse(IWindow window)
   at workspacer.WorkspaceManager.UpdateWindow(IWindow window, WindowUpdateType type)|System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')
   at System.Collections.Generic.List`1.set_Item(Int32 index, T value)
   at workspacer.Workspace.SwapWindows(IWindow left, IWindow right)
   at workspacer.WorkspaceManager.TrySwapWindowToMouse(IWindow window)
   at workspacer.WorkspaceManager.UpdateWindow(IWindow window, WindowUpdateType type)

```

**Comment by Aareon** [comment]
This *should* be a relatively simple fix. Thank you for sharing.
