### ISSUE TITLE
[error] Arithmetic operation resulted in an overflow

### ISSUE THREAD

**Issue by 2gn** [workspacer/workspacer#513]
Workspacer starts with the following error:

```powershell
Unhandled exception. System.OverflowException: Arithmetic operation resulted in an overflow.
   at System.IntPtr.op_Explicit(IntPtr value)
   at workspacer.ConsoleHelper.get_IsConsoleShowing()
   at workspacer.ConsoleHelper.set_IsConsoleShowing(Boolean value)
   at workspacer.ConsoleHelper.Initialize()
   at workspacer.Watcher.Program.Main(String[] args)
```
Here is my configuration 

```csharp
#r "C:\Program Files\workspacer\workspacer.Shared.dll"
#r "C:\Program Files\workspacer\plugins\workspacer.Bar\workspacer.Bar.dll"
#r "C:\Program Files\workspacer\plugins\workspacer.ActionMenu\workspacer.ActionMenu.dll"
#r "C:\Program Files\workspacer\plugins\workspacer.FocusIndicator\workspacer.FocusIndicator.dll"

using System;
using workspacer;
// using workspacer.Bar;
// using workspacer.ActionMenu;
// using workspacer.FocusIndicator;

Action<IConfigContext> doConfig = (context) =>
{
    // Uncomment to switch update branch (or to disable updates)
    //context.Branch = Branch.None;

    // context.AddBar();
    // context.AddFocusIndicator();
    // var actionMenu = context.AddActionMenu();
    KeyModifiers mod = KeyModifiers.Alt;

    context.Keybinds.Unsubscribe(mod, Keys.Space);

    context.WorkspaceContainer.CreateWorkspaces("1", "2", "3", "4", "5");
    context.CanMinimizeWindows = true; // false by default
};
return doConfig;
```
I'm disabling Alt+Space because it conflicts with PowerToys Run

**Comment by 2gn** [comment]
dupe of #511, sorry!
